### ISSUE TITLE
Server tired

### ISSUE THREAD

**Issue by codeplay-code** [forkbb/forkbb#28]
New release Server tired

**Comment by MioVisman** [comment]
Open `\app\log\` folder and see last file (2023-11-04.log or 2023-11-05.log?)
Show the contents of the file here (ip in the text can be removed)

**Comment by codeplay-code** [comment]
2023-11-05 09:58:32 [error] PHP OTHER_ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.friendly_name' in 'field list' in .../app/Core/DB.php:[398]	{"exception":"PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.friendly_name' in 'field list' in .../app/Core/DB.php:398\nStack trace:\n#0 .../app/Core/DB.php(398): PDO->prepare()\n#1 .../app/Models/Forum/Refresh.php(48): ForkBB\\Core\\DB->query()\n#2 .../app/Models/Manager.php(68): ForkBB\\Models\\Forum\\Refresh->refresh()\n#3 .../app/Models/Forum/Forums.php(72): ForkBB\\Models\\Manager->__call()\n#4 .../app/Core/Container.php(122): ForkBB\\Models\\Forum\\Forums->init()\n#5 .../app/Models/Pages/Index.php(41): ForkBB\\Core\\Container->__get()\n#6 .../app/Controllers/Routing.php(870): ForkBB\\Models\\Pages\\Index->view()\n#7 .../app/Core/Container.php(122): ForkBB\\Controllers\\Routing->routing()\n#8 .../app/bootstrap.php(80): ForkBB\\Core\\Container->__get()\n#9 .../index.php(14): require('/home/u87157643...')\n#10 {main}","headers":{"REMOTE_ADDR":"87.2.84.87","HTTP_USER_AGENT":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}}
2023-11-05 09:58:34 [error] PHP OTHER_ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.friendly_name' in 'field list' in .../app/Core/DB.php:[398]	{"exception":"PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.friendly_name' in 'field list' in .../app/Core/DB.php:398\nStack trace:\n#0 .../app/Core/DB.php(398): PDO->prepare()\n#1 .../app/Models/Forum/Refresh.php(48): ForkBB\\Core\\DB->query()\n#2 .../app/Models/Manager.php(68): ForkBB\\Models\\Forum\\Refresh->refresh()\n#3 .../app/Models/Forum/Forums.php(72): ForkBB\\Models\\Manager->__call()\n#4 .../app/Core/Container.php(122): ForkBB\\Models\\Forum\\Forums->init()\n#5 .../app/Models/Pages/Index.php(41): ForkBB\\Core\\Container->__get()\n#6 .../app/Controllers/Routing.php(870): ForkBB\\Models\\Pages\\Index->view()\n#7 .../app/Core/Container.php(122): ForkBB\\Controllers\\Routing->routing()\n#8 .../app/bootstrap.php(80): ForkBB\\Core\\Container->__get()\n#9 .../index.php(14): require('/home/u87157643...')\n#10 {main}","headers":{"REMOTE_ADDR":"87.2.84.87","HTTP_USER_AGENT":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}}
2023-11-05 09:58:34 [error] PHP OTHER_ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.friendly_name' in 'field list' in .../app/Core/DB.php:[398]	{"exception":"PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.friendly_name' in 'field list' in .../app/Core/DB.php:398\nStack trace:\n#0 .../app/Core/DB.php(398): PDO->prepare()\n#1 .../app/Models/Forum/Refresh.php(48): ForkBB\\Core\\DB->query()\n#2 .../app/Models/Manager.php(68): ForkBB\\Models\\Forum\\Refresh->refresh()\n#3 .../app/Models/Forum/Forums.php(72): ForkBB\\Models\\Manager->__call()\n#4 .../app/Core/Container.php(122): ForkBB\\Models\\Forum\\Forums->init()\n#5 .../app/Models/Pages/Index.php(41): ForkBB\\Core\\Container->__get()\n#6 .../app/Controllers/Routing.php(870): ForkBB\\Models\\Pages\\Index->view()\n#7 .../app/Core/Container.php(122): ForkBB\\Controllers\\Routing->routing()\n#8 .../app/bootstrap.php(80): ForkBB\\Core\\Container->__get()\n#9 .../index.php(14): require('/home/u87157643...')\n#10 {main}","headers":{"REMOTE_ADDR":"87.2.84.87","HTTP_USER_AGENT":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}}
2023-11-05 09:58:34 [error] PHP OTHER_ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.friendly_name' in 'field list' in .../app/Core/DB.php:[398]	{"exception":"PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.friendly_name' in 'field list' in .../app/Core/DB.php:398\nStack trace:\n#0 .../app/Core/DB.php(398): PDO->prepare()\n#1 .../app/Models/Forum/Refresh.php(48): ForkBB\\Core\\DB->query()\n#2 .../app/Models/Manager.php(68): ForkBB\\Models\\Forum\\Refresh->refresh()\n#3 .../app/Models/Forum/Forums.php(72): ForkBB\\Models\\Manager->__call()\n#4 .../app/Core/Container.php(122): ForkBB\\Models\\Forum\\Forums->init()\n#5 .../app/Models/Pages/Index.php(41): ForkBB\\Core\\Container->__get()\n#6 .../app/Controllers/Routing.php(870): ForkBB\\Models\\Pages\\Index->view()\n#7 .../app/Core/Container.php(122): ForkBB\\Controllers\\Routing->routing()\n#8 .../app/bootstrap.php(80): ForkBB\\Core\\Container->__get()\n#9 .../index.php(14): require('/home/u87157643...')\n#10 {main}","headers":{"REMOTE_ADDR":"87.2.84.87","HTTP_USER_AGENT":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}}
2023-11-05 09:58:35 [error] PHP OTHER_ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.friendly_name' in 'field list' in .../app/Core/DB.php:[398]	{"exception":"PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.friendly_name' in 'field list' in .../app/Core/DB.php:398\nStack trace:\n#0 .../app/Core/DB.php(398): PDO->prepare()\n#1 .../app/Models/Forum/Refresh.php(48): ForkBB\\Core\\DB->query()\n#2 .../app/Models/Manager.php(68): ForkBB\\Models\\Forum\\Refresh->refresh()\n#3 .../app/Models/Forum/Forums.php(72): ForkBB\\Models\\Manager->__call()\n#4 .../app/Core/Container.php(122): ForkBB\\Models\\Forum\\Forums->init()\n#5 .../app/Models/Pages/Index.php(41): ForkBB\\Core\\Container->__get()\n#6 .../app/Controllers/Routing.php(870): ForkBB\\Models\\Pages\\Index->view()\n#7 .../app/Core/Container.php(122): ForkBB\\Controllers\\Routing->routing()\n#8 .../app/bootstrap.php(80): ForkBB\\Core\\Container->__get()\n#9 .../index.php(14): require('/home/u87157643...')\n#10 {main}","headers":{"REMOTE_ADDR":"87.2.84.87","HTTP_USER_AGENT":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}}
2023-11-05 09:58:35 [error] PHP OTHER_ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.friendly_name' in 'field list' in .../app/Core/DB.php:[398]	{"exception":"PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.friendly_name' in 'field list' in .../app/Core/DB.php:398\nStack trace:\n#0 .../app/Core/DB.php(398): PDO->prepare()\n#1 .../app/Models/Forum/Refresh.php(48): ForkBB\\Core\\DB->query()\n#2 .../app/Models/Manager.php(68): ForkBB\\Models\\Forum\\Refresh->refresh()\n#3 .../app/Models/Forum/Forums.php(72): ForkBB\\Models\\Manager->__call()\n#4 .../app/Core/Container.php(122): ForkBB\\Models\\Forum\\Forums->init()\n#5 .../app/Models/Pages/Index.php(41): ForkBB\\Core\\Container->__get()\n#6 .../app/Controllers/Routing.php(870): ForkBB\\Models\\Pages\\Index->view()\n#7 .../app/Core/Container.php(122): ForkBB\\Controllers\\Routing->routing()\n#8 .../app/bootstrap.php(80): ForkBB\\Core\\Container->__get()\n#9 .../index.php(14): require('/home/u87157643...')\n#10 {main}","headers":{"REMOTE_ADDR":"87.2.84.87","HTTP_USER_AGENT":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}}

**Comment by codeplay-code** [comment]
PHP OTHER_ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.friendly_name' in 'field list' in .../app/Core/DB.php:[398]
...

**Comment by MioVisman** [comment]
Was this a new installation or an update from a previous revision?

The friendly_name field is missing in the forums table.

**Comment by codeplay-code** [comment]
im upload file release but not upgrade server tires

**Comment by MioVisman** [comment]
Do the following:
1. In the config table, find the conf_name entry containing "i_fork_revision". Change its conf_value from 72 to 71. This can be done in phpMyAdmin, for example. 
![config](https://github.com/forkbb/forkbb/assets/5917956/8d24a9bb-356c-4919-93c8-41bf23fce38a)
2. Delete app/cache/cache_config.php file.
3. Open site and start update script.

**Comment by MioVisman** [comment]
>im upload file release but not upgrade server tires

Hmm, the update won't start? Google Translator wrote to me about some tires (from a car) :(

**Comment by MioVisman** [comment]
I checked the new installation of revision 72 - no problems.
I checked the update again from revision 71 to 72 - I also found no problems.

**Comment by codeplay-code** [comment]
server tired is solved  now what should I do to replace the files again to update?

**Comment by MioVisman** [comment]
What revision is currently installed on your server?

P.S. And turn on displaying errors on the screen while the problem persists:
/app/config/main.php
```
# development
#\error_reporting(\E_ALL);
#\ini_set('display_errors', '1');
#\ini_set('log_errors', '1');
```
replace to
```
# development
\error_reporting(\E_ALL);
\ini_set('display_errors', '1');
\ini_set('log_errors', '1');
```

**Comment by codeplay-code** [comment]
72 but it is not updated with the new release

https://ibb.co/pxMhJ4B

**Comment by MioVisman** [comment]
Revision 72 did not change the topics, this revision changed the forums:
![forumedit](https://github.com/forkbb/forkbb/assets/5917956/436b8219-3760-49df-b200-26ce8e430a31)

**Comment by codeplay-code** [comment]
[exception] => PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.friendly_name' in 'field list' in .../app/Core/DB.php:398
Stack trace:
#0 .../app/Core/DB.php(398): PDO->prepare()
#1 .../app/Models/Forum/Refresh.php(48): ForkBB\Core\DB->query()
#2 .../app/Models/Manager.php(68): ForkBB\Models\Forum\Refresh->refresh()
#3 .../app/Models/Forum/Forums.php(72): ForkBB\Models\Manager->__call()
#4 .../app/Core/Container.php(122): ForkBB\Models\Forum\Forums->init()
#5 .../app/Models/Pages/Index.php(41): ForkBB\Core\Container->__get()
#6 .../app/Controllers/Routing.php(870): ForkBB\Models\Pages\Index->view()
#7 .../app/Core/Container.php(122): ForkBB\Controllers\Routing->routing()
#8 .../app/bootstrap.php(80): ForkBB\Core\Container->__get()
#9 .../index.php(14): require('/home/u87157643...')
#10 {main}
    [headers] => Array
        (
            [REMOTE_ADDR] => 87.2.84.87
            [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
        )

**Comment by codeplay-code** [comment]
> Revision 72 did not change the topics, this revision changed the forums: ![forumedit](https://user-images.githubusercontent.com/5917956/280529302-436b8219-3760-49df-b200-26ce8e430a31.png)

not change

**Comment by codeplay-code** [comment]
im upload all files from server but no upgrade not change

**Comment by MioVisman** [comment]
>im upload all files from server but no upgrade not change

![forumstable](https://github.com/forkbb/forkbb/assets/5917956/713aca79-9bfd-461c-9009-46ac31f2f1e1)

**Comment by codeplay-code** [comment]
that is present in the database but it doesn't work... tried reinstalling again

**Comment by codeplay-code** [comment]
solved
